name: Check Completeness

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Testcases
      run: python test_battery_monitor.py
    - name: all entries made
      run: bash ./.github/workflows/check-complete.sh
